/**
 * Curated capture-phase listeners (~80/20 common UI events). Loaded before content.js.
 * @see https://developer.mozilla.org/en-US/docs/Web/API/Event
 */
globalThis.BROWSERCLAW_DOM_CAPTURE_EVENT_TYPES = Object.freeze([
  "pointerover",
  "pointerenter",
  "pointerdown",
  "pointermove",
  "pointerup",
  "pointercancel",
  "pointerout",
  "pointerleave",
  "gotpointercapture",
  "lostpointercapture",
  "mouseover",
  "mouseenter",
  "mousedown",
  "mousemove",
  "mouseup",
  "mouseout",
  "mouseleave",
  "click",
  "dblclick",
  "auxclick",
  "contextmenu",
  "touchstart",
  "touchmove",
  "touchend",
  "touchcancel",
  "keydown",
  "keyup",
  "beforeinput",
  "input",
  "change",
  "focus",
  "blur",
  "focusin",
  "focusout",
  "compositionstart",
  "compositionupdate",
  "compositionend",
  "dragstart",
  "drag",
  "dragend",
  "dragenter",
  "dragleave",
  "dragover",
  "drop",
  "cut",
  "copy",
  "paste",
  "selectstart",
  "select",
  "selectionchange",
  "scroll",
  "scrollend",
  "wheel",
  "resize",
  "visibilitychange",
  "submit",
  "reset",
  "invalid",
]);

/** Event types registered with `{ passive: true }` where supported. */
globalThis.BROWSERCLAW_DOM_CAPTURE_PASSIVE_TYPES = Object.freeze(
  new Set(["scroll", "scrollend", "wheel", "touchstart", "touchmove", "touchend", "touchcancel"]),
);

globalThis.BROWSERCLAW_DOM_EVENT_LOG_MAX = 200;
